---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "cronus.fullname" . }}
  labels:
    app: {{ template "cronus.fullname" . }}
    role: {{ template "cronus.role" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storageClass }}
  storageClassName: {{ .Values.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.store.size }}