# Default values for cronus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: codefresh/cronus
  tag: 0.1
  pullPolicy: IfNotPresent

# set log level
logLevel: debug

# set event handler type and kind
event:
  type: cron
  kind: codefresh

# Hermes Service name - deafult to "<release>-hermes"
# hermesService: "..."
  
service:
  name: cronus
  type: ClusterIP
  externalPort: 80
  internalPort: 8080

# BoltDb store size
store:
  size: 1Gi